### ISSUE TITLE
Errors when running composer dump autoload

### ISSUE THREAD

**Issue by aeu** [craftcms/mandrill#5] opened 2021-09-10 20:59 UTC
### Description
When I run composer dump-autoload -a, I get a ton of console errors.

### Steps to reproduce

1. install mandrill plugin
2. run composer dump-autoload -a

### Additional info

- Craft version: Craft CMS 3.7.12
- PHP version: PHP 7.3.25 (cli) (built: Nov 24 2020 11:10:55) ( NTS )
- Database driver & version: mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1
- Plugins & versions:

```
Class Mandrill_Error located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_HttpError located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_ValidationError located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Key located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_PaymentRequired located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Subaccount located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Template located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_ServiceUnavailable located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Message located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Tag_Name located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Reject located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Sender located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Url located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_TrClass Mandrill_Error located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_HttpError located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_ValidationError located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Key located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_PaymentRequired located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Subaccount located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Template located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_ServiceUnavailable located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Message located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Tag_Name located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Reject located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Sender located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Url located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_TrackingDomain located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Template located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Webhook located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_InboundDomain located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_InboundRoute located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Export located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_IP_ProvisionLimit located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Pool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_NoSendingHistory located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_PoorReputation located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_IP located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_EmptyDefaultPool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_DeleteDefaultPool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
CackingDomain located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_Template located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Webhook located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_InboundDomain located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_InboundRoute located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Export located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_IP_ProvisionLimit located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_Pool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_NoSendingHistory located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_PoorReputation located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_IP located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_EmptyDefaultPool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_DeleteDefaultPool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_DeleteNonEmptyPool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_CustomDNS located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_CustomDNSPending located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Metadata_FieldLimit located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_MetadataField located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
lass Mandrill_Invalid_DeleteNonEmptyPool located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_CustomDNS located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Invalid_CustomDNSPending located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Metadata_FieldLimit located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
Class Mandrill_Unknown_MetadataField located in ./vendor/mandrill/mandrill/src/Mandrill/Exceptions.php does not comply with psr-0 autoloading standard. Skipping.
```

**Comment by brandonkelly** [comment] 2021-09-15 21:24
This is a duplicate of #4.

**Closed as completed by brandonkelly** 2021-09-15 21:24 UTC
Labels: bug
